fanotify: Move __kernel_fsid_t definition to correct place
This fixes errors:

fanotify.h:149:55: error: unknown type name ‘__kernel_fsid_t’
 static inline void fanotify_get_fid(const char *path, __kernel_fsid_t *fsid,
                                                       ^~~~~~~~~~~~~~~
fanotify13.c:47:2: error: unknown type name ‘__kernel_fsid_t’
  __kernel_fsid_t fsid;

Fixes: b8aebc835 ("fanotify: Fix missing __kernel_fsid_t definition")

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>