pkeys: Fix uclibc build caused by conflicting signature
uClibc defines pkey_{alloc,free,mprotect} signatures in
<bits/mman-shared.h>, which is included by <bits/mman-linux.h>. Because
it does not implement them, our implementation signature conflicts, as
it uses static. Add 'ltp_' prefix to our helper functions (suggested by Jan).

Fixed build error:
In file included from pkey01.c:32:0:
pkey.h:18:19: error: static declaration of ‘pkey_mprotect’ follows non-static declaration
 static inline int pkey_mprotect(void *addr, size_t len, int prot, int pkey)
                   ^
In file included from /opt/br-test-pkg/br-arm-full/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/bits/mman-linux.h:115:0,
                 from /opt/br-test-pkg/br-arm-full/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/bits/mman.h:40,
                 from /opt/br-test-pkg/br-arm-full/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/sys/mman.h:41,
                 from pkey01.c:29:
/opt/br-test-pkg/br-arm-full/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/bits/mman-shared.h:73:5: note: previous declaration of ‘pkey_mprotect’ was here
 int pkey_mprotect (void *__addr, size_t __len, int __prot, int __pkey) __THROW;
     ^
In file included from pkey01.c:32:0:

Found with test-pkg tool from Buildroot distribution.

Fixes: 90c2dc89f ("pkey: add test for memory protection keys")

Reported-by: Petr Vorel <petr.vorel@gmail.com>
Suggested-by: Jan Stancek <jstancek@redhat.com>
Signed-off-by: Petr Vorel <pvorel@suse.cz>
[Upstream status: 5c3f08d31a4619454ef4db3501dbf2679867ba7f]