bpf: Fix linking on old distros
Centos 6 (glibc 2.12):

testcases/kernel/syscalls/bpf/../../../../include/lapi/bpf.h:557: multiple definition of `ptr_to_u64'
/tmp/cckcGS9G.o:testcases/kernel/syscalls/bpf/../../../../include/lapi/bpf.h:557: first defined here
bpf_common.o: In function `bpf':
testcases/kernel/syscalls/bpf/../../../../include/lapi/bpf.h:562: multiple definition of `bpf'
/tmp/cckcGS9G.o:testcases/kernel/syscalls/bpf/../../../../include/lapi/bpf.h:562: first defined here
collect2: ld returned 1 exit status
make: *** [bpf_map01] Error 1

Fixes: 71388f3e4 ("Split off executable code from bpf/bpf_common.h")

Signed-off-by: Petr Vorel <pvorel@suse.cz>