nfsv4/acl: Remove unneeded malloc(sizeof(FILE))
FILE incomplete type under musl (comply C11 [1]).
malloc(sizeof(FILE)) is not needed anyway, thus remove.

This fixes build on musl (at least):
acl1.c:51:23: error: invalid application of 'sizeof' to incomplete type 'FILE' {aka 'struct _IO_FILE'}
  fptr = malloc(sizeof(FILE));

Fixes: 618fd23eb ("Initial add of acl testsuite from Bull")

[1] https://www.openwall.com/lists/musl/2019/01/16/1

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>
[Upstream status: 7eae073fda17a94a36893337b5a5d639024d571c]